### ISSUE TITLE
Error: DiscoverMatrix

### ISSUE THREAD

**Issue by tatsuroyamaguchi** [NKI-CCB/DISCOVER#22] opened 2023-04-12 14:46 UTC
I ran Set up according to "An introduction to DISCOVER". However, when I run discover.DiscoverMatrix(mut), I get the following error:

<img width="845" alt="スクリーンショット 2023-04-12 23 36 41" src="https://user-images.githubusercontent.com/76607586/231492024-b70760e5-84c9-4f23-82ec-10d77b50c949.png">

Could you help me? Thanks!

M1 mac
MacOS 13.3.1
Jupyter Notebook 6.5.4
Python3.8

**Comment by sashitt2** [comment] 2023-05-04 05:12
I seems like `__array_wrap__` has been deprecated (https://pandas.pydata.org/docs/whatsnew/v1.5.0.html?highlight=__array_wrap__#other-deprecations).

I installed an older version of pandas (1.4.4) to circumvent this issue. If you use conda, you could try  `conda install pandas==1.4.4`

**Comment by tatsuroyamaguchi** [comment] 2023-05-07 01:53
Thanks a lot!

**Comment by scanisius** [comment] 2023-05-12 14:05
Thanks to you both for reporting and finding the cause of this issue. The new [v0.9.5](https://github.com/NKI-CCB/DISCOVER/releases/tag/py_v0.9.5) release has a fix for this issue that is compatible with newer versions of pandas.

**Comment by tatsuroyamaguchi** [comment] 2023-05-16 02:37
Many thanks for your kind correspondence!

**Closed** 2023-05-18 14:03 UTC
